%global tl_name pkfix
%global tl_revision 26032

Name:		texlive-%{tl_name}
Epoch:		1
Version:	1.7
Release:	%{tl_revision}.1
Summary:	Replace pk fonts in PostScript with Type 1 fonts
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/support/pkfix
License:	lppl1.3
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/pkfix.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/pkfix.doc.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
Requires:	texlive(pkfix.bin)
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
The perl script pkfix looks for DVIPSBitmapFont comments in PostScript
files, generated by 'not too old' dvips, and replaces them by type 1
versions of the fonts, if possible.

